### ISSUE TITLE
Feature request : supporting bearer tokens?

### ISSUE THREAD

**Issue by minhducsun2002** [Kiritsu/OsuSharp#10]
I don't currently see a way to use bearer tokens with the library - I'm implementing OAuth2 with the Authorization Code grant, and I want to be able to fetch the associated user data.

Could you please add support for this use case? Thank you.

**Comment by Kiritsu** [comment]
Hey! It is actually supported. The Authorization Code grant gives the following information:
- Access Token
- Refresh Token
- Expiration

You can then use `IOsuClient#UpdateAccessToken` which takes these three parameters in the same order. The library, then, will know that you're doing Authorization Code grant, because of the refresh token. Then, you can just fetch whatever you want and the library will automatically refresh the token when it expires.

**Comment by minhducsun2002** [comment]
Ah, that wasn't really intuitive for me though. Thanks anyway!

**Comment by Kiritsu** [comment]
Yeah. It lacks of guides for now. I’m also open to proposal to make the public interface more intuitive if you have any idea.
