### ISSUE TITLE
No way to get beatmap set

### ISSUE THREAD

**Issue by takoz53** [Kiritsu/OsuSharp#2]
https://osu.ppy.sh/beatmapsets/938144

For instance this link. It is taiko, so you need to:
`Instance.GetBeatmap(beatmapID, OsuSharp.Enums.BeatmapType.ByBeatmap, OsuSharp.Enums.GameMode.Taiko);`

The problem is, you need to know it is TAIKO to get the map.
If you don't know what mode it is, you can't get information about a set.

you'd probably end up doing something like..

`try {
                    beatmap = Instance.GetBeatmap(beatmapID, OsuSharp.Enums.BeatmapType.ByBeatmap, OsuSharp.Enums.GameMode.Standard);
                } catch {
                    try {
                        Instance.GetBeatmap(beatmapID, OsuSharp.Enums.BeatmapType.ByBeatmap, OsuSharp.Enums.GameMode.Taiko);
                    } catch {
                        try {
                            Instance.GetBeatmap(beatmapID, OsuSharp.Enums.BeatmapType.ByBeatmap, OsuSharp.Enums.GameMode.Mania);
                        } catch {
                            try {
                                Instance.GetBeatmap(beatmapID, OsuSharp.Enums.BeatmapType.ByBeatmap, OsuSharp.Enums.GameMode.Catch);
                            } catch {
                                beatmap = null;
                            }
                        }
                    }
                }
            }`

or some shit to guess which gamemode it might be. Is there a proper way to handle getting beatmapsets?

**Comment by Kiritsu** [comment]
Hello! 

I'm sorry you ran into this issue. Indeed currently there are no ways to get a map by beatmapsetid without specifying it's gamemode and it's my fault. 

The entire library is a bit fucked up because of the documentation not being clear enough. I started a rewrite but only beatmap/replay endpoints are properly mapped. (See branch rewrite) tho I mostly stopped it because of a possible incoming V2 and a lack of time. 

If you can wait this weekend, I could probably rush the rewrite and release a version of it.

**Comment by takoz53** [comment]
thank you for the quick answer. Do I understand correct that I can get beatmap/beatmapsets on the rewrite already? I only need those. I really like how you implemented everything. If those already exist on the rewrite, I can use those as I don't need other features. Icould wait for a rewrite until the weekend as well though.

**Comment by Kiritsu** [comment]
Yes you can use `OsuClient#GetBeatmapsetAsync(long, CancellationToken = default)` for a beatmapset without specifying the game mode on the branch rewrite.

I have worked on this branch and already added get_user endpoint and multiplayer endpoint. I think I could even finish the rewrite today, but this still would need a lot of testing.

Honestly anyway I'd not recommend to use the latest nuget package or the master branch because a lot of entities are invalid, can be null because of the osu!api inconsistencies. And I tried to fix that in the rewrite. The rewrite will also have multiple way to retrieve entities from another entities. For exemple, in a beatmap, you have the author_id of the beatmap, it would be possible to directly request the User object associated with that author_id, etc. It's a complete new design! (For the history part, this project was my first real programming project, so it has lots of imperfections... And it didn't support everything too. I was ignoring some properties because I didn't know how to use them... lol)

EDIT: But keep in mind that the branch rewrite has been barely tested. Tho, if you encounter any issue, I can fix it probably instantly. :D

**Comment by Kiritsu** [comment]
And btw, when the documentation of the api v2 is ready, I'll probably implement it too, but it seems like we got some times... lol

**Comment by takoz53** [comment]
I understand. I'll give it a shot and I'll give you a message when I have issues. If you want we could add each other from discord for faster messaging as well :) たここ#1196 if interested.

**Comment by Kiritsu** [comment]
Done! :) (Seven#6605)

**Comment by Kiritsu** [comment]
Alright, the rewrite is completed, has been merged on master and a new nuget package has been pushed (5.0.1) - closing the issue. If you have any issue, feel free to open a new issue!
